const crypto=require('node:crypto');
const bcrypt=require('bcryptjs');
const request=require('supertest');
const pool=require('../db');
const {migrate}=require('../migrate');
const {createApp}=require('../server');
const sales=require('../services/sales');
const connectors=require('../services/connectors');

const ids={tenant:'10000000-0000-4000-8000-000000000001',otherTenant:'10000000-0000-4000-8000-000000000002',operator:'20000000-0000-4000-8000-000000000001',reviewer:'20000000-0000-4000-8000-000000000002',manager:'20000000-0000-4000-8000-000000000003',other:'20000000-0000-4000-8000-000000000004'};
const password='long-enough-test-password';let app,tokens={},leadId,outreachId;
const future=()=>{const date=new Date();date.setUTCDate(date.getUTCDate()+1);date.setUTCHours(14,0,0,0);return date.toISOString()};
async function login(email,tenant='acme',loginPassword=password){return (await request(app).post('/api/auth/login').send({tenant,email,password:loginPassword})).body.token}
async function seed(){await pool.query(`TRUNCATE sales_audit_events,sales_handoffs,sales_provider_events,sales_outbox,sales_outreach,sales_suppressions,sales_consent_events,sales_sync_events,sales_leads,sales_accounts,sales_connectors,sales_identities,sales_tenants RESTART IDENTITY CASCADE`);const hash=await bcrypt.hash(password,4);await pool.query(`INSERT INTO sales_tenants(id,slug,name) VALUES($1,'acme','Acme'),($2,'other','Other')`,[ids.tenant,ids.otherTenant]);for(const[id,tenant,email,name,role]of[[ids.operator,ids.tenant,'op@example.test','Operator','operator'],[ids.reviewer,ids.tenant,'review@example.test','Reviewer','reviewer'],[ids.manager,ids.tenant,'manager@example.test','Manager','manager'],[ids.other,ids.otherTenant,'other@example.test','Other','manager']])await pool.query(`INSERT INTO sales_identities(id,tenant_id,email,password_hash,display_name,role) VALUES($1,$2,$3,$4,$5,$6)`,[id,tenant,email,hash,name,role]);}
function leadPayload(overrides={}){return{eventId:crypto.randomUUID(),externalCrmId:'CRM-001',displayName:'Ada Lovelace',contactReference:'vault://contacts/001',region:'EU',sourceSystem:'salesforce',sourceRevision:'rev-1',sourceObservedAt:new Date().toISOString(),attribution:{source:'conference'},...overrides}}

beforeAll(async()=>{await migrate();await migrate();await seed();app=createApp();tokens.operator=await login('op@example.test');tokens.reviewer=await login('review@example.test');tokens.manager=await login('manager@example.test');tokens.other=await login('other@example.test','other')});
afterAll(async()=>{vi.restoreAllMocks();await pool.end()});

describe.sequential('governed sales workflow',()=>{
  it('applies migrations replay-safely and authenticates with short scoped sessions',async()=>{const bad=await request(app).post('/api/auth/login').send({tenant:'acme',email:'op@example.test',password:'incorrect-password'});expect(bad.status).toBe(401);const session=await request(app).get('/api/auth/session').set('authorization',`Bearer ${tokens.operator}`);expect(session.status).toBe(200);expect(session.body.user.role).toBe('operator')});
  it('disables public account creation',async()=>{expect((await request(app).post('/api/auth/register').send({})).status).toBe(403)});
  it('ingests a CRM lead and deduplicates an exact replay',async()=>{const body=leadPayload();const first=await request(app).post('/api/sales/sync/crm/leads').set('authorization',`Bearer ${tokens.operator}`).send(body);expect(first.status).toBe(200);expect(first.body.replay).toBe(false);leadId=first.body.lead.id;const replay=await request(app).post('/api/sales/sync/crm/leads').set('authorization',`Bearer ${tokens.operator}`).send(body);expect(replay.body).toEqual({replay:true})});
  it('rejects reuse of a sync event id with a different payload',async()=>{const base=leadPayload({eventId:'fixed-conflict-event',sourceRevision:'rev-2',sourceObservedAt:new Date(Date.now()+1000).toISOString()});expect((await request(app).post('/api/sales/sync/crm/leads').set('authorization',`Bearer ${tokens.operator}`).send(base)).status).toBe(200);const conflict=await request(app).post('/api/sales/sync/crm/leads').set('authorization',`Bearer ${tokens.operator}`).send({...base,displayName:'Altered'});expect(conflict.status).toBe(409);expect(conflict.body.code).toBe('sync_conflict')});
  it('rejects stale source updates',async()=>{const stale=leadPayload({eventId:'stale-event',sourceRevision:'rev-old',sourceObservedAt:'2020-01-01T00:00:00.000Z'});const response=await request(app).post('/api/sales/sync/crm/leads').set('authorization',`Bearer ${tokens.operator}`).send(stale);expect(response.status).toBe(409);expect(response.body.code).toBe('stale_sync')});
  it('enforces tenant isolation',async()=>{const response=await request(app).get('/api/sales/leads').set('authorization',`Bearer ${tokens.other}`);expect(response.status).toBe(200);expect(response.body).toEqual([])});
  it('enforces explicit lifecycle transitions and ownership',async()=>{const invalid=await request(app).post(`/api/sales/leads/${leadId}/transition`).set('authorization',`Bearer ${tokens.operator}`).send({state:'converted',reason:'skip'});expect(invalid.status).toBe(409);const qualified=await request(app).post(`/api/sales/leads/${leadId}/transition`).set('authorization',`Bearer ${tokens.operator}`).send({state:'qualified',reason:'verified'});expect(qualified.body.lifecycle_state).toBe('qualified')});
  it('requires current regional consent before outreach',async()=>{const response=await request(app).post('/api/sales/outreach').set('authorization',`Bearer ${tokens.operator}`).send({leadId,channel:'email',templateId:'intro-v1',campaignId:'launch',idempotencyKey:'outreach-before-consent',scheduledAt:future()});expect(response.status).toBe(409);expect(response.body.code).toBe('consent_required')});
  it('records consent evidence and requires independent human review',async()=>{const consent=await request(app).post('/api/sales/consent').set('authorization',`Bearer ${tokens.operator}`).send({leadId,channel:'email',purpose:'sales outreach',state:'granted',lawfulBasis:'consent',sourceSystem:'consent-center',eventId:'consent-1',sourceObservedAt:new Date().toISOString()});expect(consent.status).toBe(200);const submitted=await request(app).post('/api/sales/outreach').set('authorization',`Bearer ${tokens.manager}`).send({leadId,channel:'email',templateId:'intro-v1',campaignId:'launch',idempotencyKey:'outreach-reviewed-001',scheduledAt:future()});expect(submitted.status).toBe(200);outreachId=submitted.body.outreach.id;const selfReview=await request(app).post(`/api/sales/outreach/${outreachId}/review`).set('authorization',`Bearer ${tokens.manager}`).send({decision:'approve',notes:'I approve my own request'});expect(selfReview.status).toBe(409);expect(selfReview.body.code).toBe('separation_of_duties')});
  it('queues approved outreach exactly once',async()=>{const approved=await request(app).post(`/api/sales/outreach/${outreachId}/review`).set('authorization',`Bearer ${tokens.reviewer}`).send({decision:'approve',notes:'Consent and content reviewed'});expect(approved.body.state).toBe('queued');const rows=await pool.query(`SELECT * FROM sales_outbox WHERE aggregate_id=$1 AND event_type='outreach.send'`,[outreachId]);expect(rows.rowCount).toBe(1)});
  it('retries transient connector failures without duplicate jobs',async()=>{const spy=vi.spyOn(connectors,'deliver').mockRejectedValueOnce(Object.assign(new Error('temporary outage'),{retryable:true})).mockResolvedValue({provider:'mail',providerMessageId:'msg-1'});let sawRetry=false;for(let i=0;i<4;i++){const result=await sales.processNextOutbox('test-worker');if(result?.state==='retry'){sawRetry=true;break}}expect(sawRetry).toBe(true);expect(spy).toHaveBeenCalled()});
  it('successfully resumes a due retry with the same delivery key',async()=>{await pool.query(`UPDATE sales_outbox SET next_attempt_at=now() WHERE state='retry'`);const result=await sales.processNextOutbox('test-worker');expect(result.state).toBe('succeeded')});
  it('accepts signed provider delivery callbacks and deduplicates replay',async()=>{const payload={eventId:'provider-1',type:'outreach.delivered',outreachId,leadId,channel:'email',occurredAt:new Date().toISOString(),providerMessageId:'msg-1'};const raw=JSON.stringify(payload);const timestamp=String(Math.floor(Date.now()/1000));const signature=crypto.createHmac('sha256',process.env.OUTREACH_WEBHOOK_SECRET||'local-outreach-webhook-secret-32-chars').update(`${timestamp}.${raw}`).digest('hex');const send=()=>request(app).post('/api/webhooks/outreach/mail').set('content-type','application/json').set('x-sales-tenant','acme').set('x-webhook-timestamp',timestamp).set('x-webhook-signature',signature).send(raw);expect((await send()).body.replay).toBe(false);expect((await send()).body.replay).toBe(true);expect((await pool.query('SELECT lifecycle_state FROM sales_leads WHERE id=$1',[leadId])).rows[0].lifecycle_state).toBe('contacted')});
  it('converts the lead to an attributed account and reports real metrics',async()=>{const converted=await request(app).post(`/api/sales/leads/${leadId}/transition`).set('authorization',`Bearer ${tokens.operator}`).send({state:'converted',reason:'signed agreement'});expect(converted.body.account_id).toBeTruthy();const dashboard=await request(app).get('/api/sales/dashboard').set('authorization',`Bearer ${tokens.operator}`);expect(dashboard.body.converted).toBe(1);expect(dashboard.body.conversionRate).toBe(1)});
  it('applies provider opt-out suppression and blocks future contact',async()=>{const second=(await request(app).post('/api/sales/sync/crm/leads').set('authorization',`Bearer ${tokens.manager}`).send(leadPayload({eventId:'lead-2',externalCrmId:'CRM-002',region:'US',sourceObservedAt:new Date(Date.now()+3000).toISOString()}))).body.lead;const payload={eventId:'optout-1',type:'contact.opted_out',leadId:second.id,channel:'email',occurredAt:new Date().toISOString()};expect((await sales.providerEvent(ids.tenant,'mail',payload)).replay).toBe(false);const active=await pool.query(`SELECT 1 FROM sales_suppressions WHERE lead_id=$1 AND active`,[second.id]);expect(active.rowCount).toBe(1)});
  it('supports controlled ownership handoff',async()=>{const third=(await request(app).post('/api/sales/sync/crm/leads').set('authorization',`Bearer ${tokens.operator}`).send(leadPayload({eventId:'lead-3',externalCrmId:'CRM-003',region:'CA',sourceObservedAt:new Date(Date.now()+4000).toISOString()}))).body.lead;await request(app).post(`/api/sales/leads/${third.id}/transition`).set('authorization',`Bearer ${tokens.operator}`).send({state:'qualified',reason:'verified'});const response=await request(app).post(`/api/sales/leads/${third.id}/handoff`).set('authorization',`Bearer ${tokens.operator}`).send({toOwnerId:ids.manager,reason:'manager specialization required'});expect(response.body.status).toBe('accepted');expect((await pool.query('SELECT owner_id,lifecycle_state FROM sales_leads WHERE id=$1',[third.id])).rows[0]).toMatchObject({owner_id:ids.manager,lifecycle_state:'handed_off'})});
  it('applies deduplicated enrichment evidence without exposing connector credentials',async()=>{const observedAt=new Date(Date.now()+20_000).toISOString();const body={eventId:'enrich-1',leadId,sourceSystem:'approved-enricher',sourceObservedAt:observedAt,attributes:{employeeBand:'100-250',verified:true},qualityFlags:['verified_company']};const first=await request(app).post('/api/sales/sync/enrichment').set('authorization',`Bearer ${tokens.manager}`).send(body);expect(first.body.replay).toBe(false);const replay=await request(app).post('/api/sales/sync/enrichment').set('authorization',`Bearer ${tokens.manager}`).send(body);expect(replay.body.replay).toBe(true);const stored=(await pool.query('SELECT attribution,quality_flags FROM sales_leads WHERE id=$1',[leadId])).rows[0];expect(stored.attribution.enrichment.source).toBe('approved-enricher');expect(stored.quality_flags).toContain('verified_company')});
  it('persists calendar lifecycle events idempotently',async()=>{const body={eventId:'calendar-sync-1',externalEventId:'meeting-001',leadId,state:'completed',startsAt:future(),sourceSystem:'calendar-provider',sourceObservedAt:new Date(Date.now()+30_000).toISOString()};expect((await request(app).post('/api/sales/sync/calendar').set('authorization',`Bearer ${tokens.manager}`).send(body)).body.replay).toBe(false);expect((await request(app).post('/api/sales/sync/calendar').set('authorization',`Bearer ${tokens.manager}`).send(body)).body.replay).toBe(true);expect((await pool.query('SELECT state FROM sales_calendar_engagements WHERE external_event_id=$1',['meeting-001'])).rows[0].state).toBe('completed')});
  it('lets managers configure connector references but never stores the secret',async()=>{const saved=await request(app).put('/api/sales/connectors').set('authorization',`Bearer ${tokens.manager}`).send({kind:'crm',provider:'salesforce',endpoint:'https://connector.example.test/events',credentialReference:'acme_salesforce',sourceContractReference:'contract://salesforce/v2',enabled:true});expect(saved.status).toBe(200);expect(saved.body.credential_reference).toBe('acme_salesforce');expect(JSON.stringify(saved.body)).not.toContain('secret-value');const listed=await request(app).get('/api/sales/connectors').set('authorization',`Bearer ${tokens.manager}`);expect(listed.body).toHaveLength(1)});
  it('provisions and revokes tenant identities with token invalidation',async()=>{const email='auditor@example.test';const identityPassword='another-long-test-password';const created=await request(app).post('/api/sales/identities').set('authorization',`Bearer ${tokens.manager}`).send({email,displayName:'Auditor',role:'auditor',password:identityPassword});expect(created.status).toBe(200);const auditorToken=await login(email,'acme',identityPassword);expect((await request(app).get('/api/sales/audit/verify').set('authorization',`Bearer ${auditorToken}`)).status).toBe(200);expect((await request(app).delete(`/api/sales/identities/${created.body.id}`).set('authorization',`Bearer ${tokens.manager}`)).status).toBe(200);expect((await request(app).get('/api/auth/session').set('authorization',`Bearer ${auditorToken}`)).status).toBe(401)});
  it('keeps a verifiable append-only audit chain',async()=>{const verified=await request(app).get('/api/sales/audit/verify').set('authorization',`Bearer ${tokens.manager}`);expect(verified.body.valid).toBe(true);const event=(await pool.query('SELECT id FROM sales_audit_events LIMIT 1')).rows[0];await expect(pool.query(`UPDATE sales_audit_events SET action='tampered' WHERE id=$1`,[event.id])).rejects.toThrow(/append-only/)});
  it('rejects unsigned callbacks and reports schema health',async()=>{expect((await request(app).post('/api/webhooks/outreach/mail').send({})).status).toBe(401);expect((await request(app).get('/api/health')).body.status).toBe('ok')});
});
