import React,{useEffect,useState}from'react';
import{apiFetch}from'../api.js';
const emptyLead={eventId:'',externalCrmId:'',displayName:'',contactReference:'',region:'US',sourceSystem:'crm',sourceRevision:'',sourceObservedAt:'',attributionSource:''};
function counts(rows=[]){return rows.map(row=>`${row.lifecycle_state||row.state}: ${row.count}`).join(' · ')||'None'}
export default function SalesOperations(){const[dashboard,setDashboard]=useState(null);const[leads,setLeads]=useState([]);const[outreach,setOutreach]=useState([]);const[lead,setLead]=useState(emptyLead);const[error,setError]=useState('');const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);
  async function refresh(){const[d,l,o]=await Promise.all([apiFetch('/api/sales/dashboard'),apiFetch('/api/sales/leads'),apiFetch('/api/sales/outreach')]);setDashboard(d);setLeads(l);setOutreach(o)}useEffect(()=>{refresh().catch(err=>setError(err.message))},[]);
  async function execute(action,success){setBusy(true);setError('');setMessage('');try{await action();setMessage(success);await refresh()}catch(err){setError(err.message)}finally{setBusy(false)}}
  async function ingest(event){event.preventDefault();await execute(()=>apiFetch('/api/sales/sync/crm/leads',{method:'POST',body:JSON.stringify({...lead,sourceObservedAt:new Date(lead.sourceObservedAt).toISOString(),attribution:lead.attributionSource?{source:lead.attributionSource}:{}})}),'CRM event applied idempotently');setLead(emptyLead)}
  async function transition(id,state){await execute(()=>apiFetch(`/api/sales/leads/${id}/transition`,{method:'POST',body:JSON.stringify({state,reason:'Operator-confirmed lifecycle update'})}),`Lead moved to ${state}`)}
  async function consent(id){await execute(()=>apiFetch('/api/sales/consent',{method:'POST',body:JSON.stringify({leadId:id,channel:'email',purpose:'sales outreach',state:'granted',lawfulBasis:'consent',sourceSystem:'consent-center',eventId:crypto.randomUUID(),sourceObservedAt:new Date().toISOString()})}),'Consent evidence recorded')}
  async function request(id){const scheduled=new Date();scheduled.setUTCDate(scheduled.getUTCDate()+1);scheduled.setUTCHours(14,0,0,0);await execute(()=>apiFetch('/api/sales/outreach',{method:'POST',body:JSON.stringify({leadId:id,channel:'email',templateId:'approved-introduction-v1',campaignId:'operator-campaign',idempotencyKey:crypto.randomUUID(),scheduledAt:scheduled.toISOString()})}),'Outreach sent for independent human review')}
  async function review(id,decision){await execute(()=>apiFetch(`/api/sales/outreach/${id}/review`,{method:'POST',body:JSON.stringify({decision,notes:`Human reviewer ${decision} decision`})}),`Review decision: ${decision}`)}
  return <div><header className="page-header"><div><h2>Sales control room</h2><p>Persistent lifecycle and evidence—not generated recommendations.</p></div><button className="secondary" onClick={()=>refresh().catch(err=>setError(err.message))}>Refresh</button></header>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}{dashboard&&<div className="metric-grid"><div className="metric"><strong>{dashboard.totalLeads}</strong><span>Leads</span></div><div className="metric"><strong>{dashboard.converted}</strong><span>Converted</span></div><div className="metric"><strong>{(dashboard.conversionRate*100).toFixed(1)}%</strong><span>Conversion</span></div><div className="metric"><strong>{dashboard.flagged}</strong><span>Quality flags</span></div><div className="metric"><strong>{dashboard.stale}</strong><span>Stale sources</span></div></div>}
    <section className="card"><h3>Inbound CRM evidence</h3><form className="form-grid" onSubmit={ingest}>{[['eventId','Stable event ID'],['externalCrmId','CRM lead ID'],['displayName','Lead name'],['contactReference','Tokenized contact reference'],['sourceRevision','Source revision'],['attributionSource','Attribution source']].map(([key,label])=><label key={key}>{label}<input value={lead[key]} onChange={e=>setLead({...lead,[key]:e.target.value})} required={key!=='attributionSource'}/></label>)}<label>Region<select value={lead.region} onChange={e=>setLead({...lead,region:e.target.value})}><option>US</option><option>CA</option><option>EU</option><option>UK</option></select></label><label>Observed at<input type="datetime-local" value={lead.sourceObservedAt} onChange={e=>setLead({...lead,sourceObservedAt:e.target.value})} required/></label><button className="primary" disabled={busy}>Apply CRM event</button></form></section>
    <section className="card"><h3>Lead lifecycle</h3><p className="muted">{counts(dashboard?.lifecycle)}</p><div className="table-wrap"><table><thead><tr><th>Lead</th><th>Region</th><th>State</th><th>Quality</th><th>Controlled actions</th></tr></thead><tbody>{leads.map(item=><tr key={item.id}><td>{item.display_name}<small>{item.external_crm_id}</small></td><td>{item.region}</td><td><span className="pill">{item.lifecycle_state}</span></td><td>{item.quality_flags?.join(', ')||'clear'}</td><td className="actions">{item.lifecycle_state==='new'&&<button onClick={()=>transition(item.id,'qualified')}>Qualify</button>}{['qualified','outreach_pending'].includes(item.lifecycle_state)&&<button onClick={()=>consent(item.id)}>Record email consent</button>}{item.lifecycle_state==='qualified'&&<button onClick={()=>request(item.id)}>Request outreach</button>}{item.lifecycle_state==='contacted'&&<button onClick={()=>transition(item.id,'converted')}>Convert</button>}</td></tr>)}</tbody></table></div></section>
    <section className="card"><h3>Human review & delivery</h3><p className="muted">{counts(dashboard?.outreach)}</p><div className="table-wrap"><table><thead><tr><th>Lead</th><th>Channel</th><th>State</th><th>Schedule</th><th>Review</th></tr></thead><tbody>{outreach.map(item=><tr key={item.id}><td>{item.lead_name}</td><td>{item.channel}</td><td><span className="pill">{item.state}</span></td><td>{new Date(item.scheduled_at).toLocaleString()}</td><td className="actions">{item.state==='review_required'&&<><button onClick={()=>review(item.id,'approve')}>Approve</button><button className="danger" onClick={()=>review(item.id,'reject')}>Reject</button></>}</td></tr>)}</tbody></table></div></section></div>}
